# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://raincrash.github.io/
baseurl: /
title: Sricharan Chiruvolu
author: Sricharan Chiruvolu
description: Personal blog and resume
avatar: logo.png
email: mail@sricharan.xyz
github: raincrash # username
twitter: sricharanized
linkedin: sricharanchiruvolu
stackoverflow: users/4134789/exlr8r   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: sricharanxyz
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]