# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bits, Pixels and Atoms
tagline:             'Random tech musing by Sricharan Chiruvolu'
description:         'Random tech musing by Sricharan Chiruvolu'
url:                 http://sricharanized.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Sricharan Chiruvolu
  url:               https://twitter.com/theraincrash
  email:             sricharanized@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/sricharanized
twitter:			http://twitter.com/theraincrash
disqus:             bitspixelsandatoms

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
