title:            Bits, Pixels and Atoms
description:      Sricharan Chiruvolu's Blog
url:              
signoff:          sricharan
disqus_shortname: bitspixelsandatoms
facebook_appid:   
google_analytics: UA-61456015-1

gems:
  - jekyll-sitemap

links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/sricharanized/
    external:     true
  - name:         Twitter
    url:          http://twitter.com/TheRaincrash/
    external:     true
  - name:         LinkedIn
    url:          http://linkedin.com/in/sricharanchiruvolu
    external:     true
  - name:         Quora
    external:     true
    url:          http://quora.com/Sricharan-Chiruvolu
  - name:         E-Mail
    external:     true
    url:          mailto:sricharanized@gmail.com
  - name:         RSS Feed
    external:     true
    url:          /feed.xml
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
